spring:
  datasource:
  #   url: jdbc:postgresql://localhost:5532/agent
  #   username: postgres
  #   password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: schema-change
    liquibase-schema: agent
  jpa:
    open-in-view: false
crnk:
  pathPrefix: /api/v1
  domainName: ""
  defaultPageLimit: 20
  maxPageLimit: 1000
  allow-unknown-attributes: true
  # The "include" query-string param is handled by our code and incorporated into the database
  # query, so we don't let Crnk automatically call findOneTarget for each null relation.
  config.lookup.behavior.default: NONE
  jpa.enabled: false
logging:
  level:
    # Reduce the logging from the rsql-jpa library, which is otherwise too excessive:
    com.github.tennaito.rsql: ERROR
